spring.application.name=loginseguro

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=loginseguro

spring.security.user.name=${ADMIN_USERNAME}
spring.security.user.password=${ADMIN_PASSWORD}

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
